name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  push_to_registry:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 
      
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
        # Build's context is the set of files located in the specified PATH or URL
        context: .
        push: true
        tags: jack2game/docker-obsidian:latest
